New resource content dec2024
alan-turing-institute/ADViCE pull request #149
Opened 2024-12-19 20:39 UTC by SteveHaben

Added content to two pages (AI and Climate Change, and Webinars), and a new page (Grand Challenge Industrial Solutions)

2025-01-06 12:05 UTC, f-rower requested changes

2025-01-06 12:05 UTC, f-rower commented on content/Resources/Grand Challenge Industrial Solutions/_index.md
Worth adding a link to the grand challenge areas so that people know what this refers to?

2025-01-06 12:05 UTC, f-rower commented on content/Resources/Grand Challenge Industrial Solutions/_index.md
> +title: "Grand Challenge Industrial Solutions"
Great idea for content!

2025-01-06 12:11 UTC, SteveHaben commented on content/Resources/Grand Challenge Industrial Solutions/_index.md
Good idea, link to this please: https://www.turing.ac.uk/sites/default/files/2023-12/advice-_ai_for_decarbonisation_challenges.pdf

2025-01-06 12:15 UTC, SteveHaben commented on content/Resources/Grand Challenge Industrial Solutions/_index.md
Ok, I added it in!

2025-01-06 12:15 UTC, SteveHaben reviewed
Thanks for looking over Fran, added in your suggestion. Happy for it to be commited and pushed

2025-01-07 11:36 UTC, f-rower approved these changes

2025-01-07 11:36 UTC, merged